CREATE FUNCTION [dbo].[InsertIntoSC]
(
)
RETURNS @returntable TABLE
(
	Sno VARCHAR(10) NOT NULL,
    Cno VARCHAR(10) NOT NULL,
	Cname VARCHAR(20) NOT NULL,
    SCgrade NUMERIC(4, 1) NULL
)
AS
BEGIN
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('801', '01', 'Database Concepts', 81.0)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('802', '01', 'Database Concepts', 59.0)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('803', '01', 'Database Concepts', 0.0)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('804', '01', 'Database Concepts', 60.0)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('805', '01', 'Database Concepts', 30.0)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('806', '01', 'Database Concepts', 90.0)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('807', '01', 'Database Concepts', 60.0)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('808', '01', 'Database Concepts', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('809', '01', 'Database Concepts', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('810', '01', 'Database Concepts', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('811', '01', 'Database Concepts', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('812', '01', 'Database Concepts', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('801', '02', 'Operating Systems', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('802', '02', 'Operating Systems', 30.0)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('803', '02', 'Operating Systems', 45.0)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('804', '02', 'Operating Systems', 80.0)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('805', '02', 'Operating Systems', 70.0)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('806', '02', 'Operating Systems', 60.0)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('807', '02', 'Operating Systems', 60.0)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('808', '02', 'Operating Systems', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('809', '02', 'Operating Systems', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('810', '02', 'Operating Systems', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('811', '02', 'Operating Systems', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('812', '02', 'Operating Systems', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('801', '03', 'Object Oriented Programming', 90.0)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('802', '03', 'Object Oriented Programming', 60.0)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('803', '03', 'Object Oriented Programming', 40.0)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('804', '03', 'Object Oriented Programming', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('805', '03', 'Object Oriented Programming', 50.0)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('806', '03', 'Object Oriented Programming', 70.0)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('807', '03', 'Object Oriented Programming', 70.0)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('808', '03', 'Object Oriented Programming', 80.0)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('809', '03', 'Object Oriented Programming', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('810', '03', 'Object Oriented Programming', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('811', '03', 'Object Oriented Programming', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('812', '03', 'Object Oriented Programming', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('801', '04', 'Java', 40.0)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('802', '04', 'Java', 0.0)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('803', '04', 'Java', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('804', '04', 'Java', 80.0)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('805', '04', 'Java', 90.0)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('806', '04', 'Java', 60.0)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('807', '04', 'Java', 70.0)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('808', '04', 'Java', 50.0)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('809', '04', 'Java', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('810', '04', 'Java', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('811', '04', 'Java', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('812', '04', 'Java', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('801', '05', 'Python', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('802', '05', 'Python', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('803', '05', 'Python', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('804', '05', 'Python', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('805', '05', 'Python', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('806', '05', 'Python', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('807', '05', 'Python', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('808', '05', 'Python', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('809', '05', 'Python', 0.0)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('810', '05', 'Python', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('811', '05', 'Python', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('812', '05', 'Python', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('801', '06', 'D Lectures', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('802', '06', 'D Lectures', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('803', '06', 'D Lectures', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('804', '06', 'D Lectures', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('805', '06', 'D Lectures', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('806', '06', 'D Lectures', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('807', '06', 'D Lectures', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('808', '06', 'D Lectures', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('809', '06', 'D Lectures', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('810', '06', 'D Lectures', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('811', '06', 'D Lectures', NULL)
	INSERT INTO [dbo].[SC](Sno, Cno, Cname, SCgrade)
	VALUES ('812', '06', 'D Lectures', NULL)
	COMMIT
	INSERT @returntable
	SELECT *
	FROM [dbo].[SC]
	RETURN
END
