CREATE TABLE [dbo].[SC]
(
	[Sno] VARCHAR(10) NOT NULL DEFAULT '000', 
    [Cno] VARCHAR(10) NOT NULL DEFAULT '00', 
	[Cname] VARCHAR(20) NOT NULL DEFAULT 'cname', 
    [SCgrade] NUMERIC(4, 1) NULL DEFAULT 0.0, 
	CONSTRAINT SC_pk PRIMARY KEY (Sno, Cno, Cname), 
	CONSTRAINT SC_fk1 FOREIGN KEY (Sno) REFERENCES S (Sno), 
	CONSTRAINT SC_fk2 FOREIGN KEY (Cno, Cname) REFERENCES C (Cno, Cname), 
	CONSTRAINT SC_SCgrade CHECK (SCgrade BETWEEN 0 AND 100 OR SCgrade IS NULL)
)
